#!/usr/bin/env python3
"""
Wrapper for run_ict_enhanced.py that properly handles [SILENT] output for cron.
Suppresses all logger output and only prints [SILENT] when no signals.
"""

import sys
import os
import io
import contextlib
import json

# Suppress all logging output
import logging
logging.disable(logging.CRITICAL)

cache_file = os.path.join(os.path.dirname(__file__), '.cache', 'generated_signals.json')

# Read existing signal count before run
before_count = 0
if os.path.exists(cache_file):
    try:
        with open(cache_file, 'r') as f:
            data = json.load(f)
            before_count = len(data)
    except:
        pass

# Capture all stdout/stderr
stdout_capture = io.StringIO()
stderr_capture = io.StringIO()

with contextlib.redirect_stdout(stdout_capture), contextlib.redirect_stderr(stderr_capture):
    # Import and run the main function
    sys.path.insert(0, os.path.dirname(__file__))
    from run_ict_enhanced import generate_all_signals
    import asyncio
    
    asyncio.run(generate_all_signals())

# Get the output
stdout_output = stdout_capture.getvalue()

# Check if NEW signals were generated by comparing cache file count
signals_generated = False
if os.path.exists(cache_file):
    try:
        with open(cache_file, 'r') as f:
            data = json.load(f)
            after_count = len(data)
            signals_generated = after_count > before_count
    except:
        pass

# If signals were generated, output the signal details
# Otherwise output exactly [SILENT]
if signals_generated:
    # Print the signal details from stdout (should be empty due to logging.disable)
    # But we can read the NEW signals from the cache file
    try:
        with open(cache_file, 'r') as f:
            data = json.load(f)
            # Print only the new signals (last N entries)
            new_signals = data[-1:] if before_count == 0 else data[before_count:]
            for sig in new_signals:
                print(f"  📈 {sig['asset']} {sig['setup_type'].upper()} {sig['direction'].upper()}: "
                      f"Entry={sig['entry_price']} SL={sig['stop_loss']} TP1={sig['take_profit_1']} "
                      f"RR={sig['risk_reward']} Conf={sig['confidence']:.0%} "
                      f"Exp={sig['expiration_time_est']} ({sig['kill_zone'] if sig['kill_zone'] else 'N/A'})")
    except:
        pass
else:
    print("[SILENT]")